#!/bin/bash

# Flags
alias la='ls -a'
alias lha='la -lh'

# Common commands
alias v='vim'

# Mistyping
alias sl='ls'
alias dc='cd'

# MRICro
alias mricro="wine ~/.wine/drive_c/Program\ Files\ \(x86\)/MRIcro/mricro.exe"
